sudo: false
cache: bundler
language: ruby

rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9
  - 1.8
  - ruby
  - ruby-head
  - jruby-9.2
  - jruby-9.1
  - jruby-9.0
  - jruby-head
  - rbx-2
  - rbx-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 1.9
    - rvm: 1.8
    - rvm: ruby
    - rvm: ruby-head
    - rvm: jruby-9.0
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-head
